version: '3.8'

services:
  person-db:
    image: postgres:15-alpine
    container_name: user-asp-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbauth
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: authdb
      POSTGRES_HOST: db
    volumes:
      - user-data:/var/lib/postgresql/data

volumes:
  user-data: